{% set name = "gimbleprep" %}
{% set version = "0.0.2b2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LohseLab/gimbleprep/archive/refs/tags/v{{ version }}.tar.gz
  sha256: f89678e9d7fbc95f08ded6e8fb9aa306fdb23e9a190d1deffb74fa0ee7c0e1d4

build:
  noarch: python
  number: 0
  entry_points:
    - gimbleprep = cli.interface:main
  script: python setup.py install --single-version-externally-managed --record=record.txt
  run_exports:
    - {{ pin_subpackage("gimbleprep", max_pin="x.x") }}

requirements:
  host:
    - python >=3.8
    - setuptools

  run:
    - python >=3.8
    - docopt
    - numpy
    - pandas
    - parallel
    - pysam
    - tqdm
    - bedtools
    - bcftools
    - samtools
    - vcflib
    - mosdepth 0.3.2
    
test:
  commands:
    - gimbleprep --help

about:
  home: https://github.com/LohseLab/gimbleprep
  summary: Preprocess fasta, bam and vcf files ready to be used by gimble
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/LohseLab/gimbleprep

extra:
  recipe-maintainers:
    - GertjanBisschop
    - DRL
