{% set name = "gimbleprep" %}
{% set version = "0.0.2b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/LohseLab/gimbleprep/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 46b8f98c95d4611290507f5f849940fac8ea713c5b5504ae0495f9d297bd56dc

build:
  noarch: python
  number: 0
  entry_points:
    - gimbleprep = cli.interface:main

requirements:
  host:
    - python >=3.8
    - setuptools

  run:
    - python >=3.8
    - docopt
    - numpy
    - pandas
    - parallel
    - pysam
    - tqdm
    - bedtools
    - bcftools
    - samtools
    - vcflib
    - mosdepth 0.3.2
    
test:
  commands:
    - gimbleprep --help

about:
  home: https://github.com/LohseLab/gimbleprep
  summary: Preprocess fasta, bam and vcf files ready to be used by gimble
  license: GPL-3.0-or-later
  license_file: LICENSE
  doc_url: https://github.com/LohseLab/gimbleprep

extra:
  recipe-maintainers:
    - GertjanBisschop
    - DRL
